default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: 0123456789
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: customers_tiflux_development